# Site settings
title: "PreyPal"
description: "Exposing PayPal's fake, alarmist email"
baseurl: "" # Leave blank for GitHub Pages
url: "https://praypal.info" # Update with your GitHub Pages URL

# Theme
theme: tactile
